#!/usr/bin/env bash
set -euo pipefail

# Reassemble parts generated by split-large-assets.sh.
# Usage: tools/join-large-asset.sh path/to/file.part output-file
PART_PREFIX=${1:?usage: $0 PART_PREFIX OUTPUT_FILE}
OUTPUT=${2:?usage: $0 PART_PREFIX OUTPUT_FILE}

parts=("$PART_PREFIX"[0-9][0-9][0-9])
[ -e "${parts[0]}" ] || { echo "No parts found for: $PART_PREFIX" >&2; exit 1; }
mkdir -p "$(dirname "$OUTPUT")"
cat -- "${parts[@]}" > "$OUTPUT"
printf 'Reassembled %s into %s\n' "$PART_PREFIX" "$OUTPUT"
